import os
import logging
import json
import re
import ast
from dataclasses import dataclass
from typing import List, Optional, Any, Union, Dict
from pathlib import Path
from dotenv import load_dotenv

from pydantic import BaseModel, Field, TypeAdapter, ValidationError, field_validator
from pydantic_ai import Agent
from pydantic_ai.models.gemini import GeminiModel

from src.common.models import Strategy

load_dotenv(Path(__file__).parent.parent.parent.parent / ".env")

# --- 1. CONFIGURATION ---
logger = logging.getLogger("CoderAgent")

keys_str = os.getenv("BACKTEST_KEYS", "")
API_KEYS = [k.strip() for k in keys_str.split(",") if k.strip()]

if not API_KEYS:
    keys_str = os.getenv("RESEARCH_KEYS", "")
    API_KEYS = [k.strip() for k in keys_str.split(",") if k.strip()]

if not API_KEYS:
    keys_str = os.getenv("GOOGLE_API_KEYS", "")
    API_KEYS = [k.strip() for k in keys_str.split(",") if k.strip()]

if not API_KEYS:
    raise ValueError("CRITICAL: No API Keys available for Coder Agent.")

def create_model(api_key: str):
    model_name = os.getenv("MODEL_SMART", "gemma-3-27b-it")
    # GeminiModel does not accept api_key in __init__, so we set it in env
    os.environ["GEMINI_API_KEY"] = api_key
    os.environ["GOOGLE_API_KEY"] = api_key
    return GeminiModel(model_name)

current_model = create_model(API_KEYS[0])

# --- 2. DEPENDENCIES ---
@dataclass
class CoderDeps:
    strategy: Strategy

# --- 3. OUTPUT SCHEMA (ROBUST) ---
class PythonStrategyCode(BaseModel):
    class_parameters: Union[str, Dict[str, Any], List[Any]] = Field(
        description="Class variables. Can be a string, dict, or list."
    )
    init_indicators: Union[str, List[str]] = Field(
        description="Indicator lines. MUST use self.I() wrapper."
    )
    next_logic: Union[str, List[str]] = Field(
        description="Logic lines for per-candle execution."
    )
    explanation: str = Field(default="Generated by AI")

    # --- VALIDATORS ---
    @field_validator('class_parameters')
    @classmethod
    def normalize_params(cls, v):
        forbidden_keys = {"lambda", "class", "try", "except", "return", "def", "from", "import", "global", "pass", "None", "True", "False", "continue", "break", "if", "else", "elif", "for", "while", "in", "is", "not", "and", "or"}

        if isinstance(v, str):
            # If it's a string, we assume it's already formatted code.
            return v

        if isinstance(v, dict):
            lines = []
            for k, val in v.items():
                sanitized_k = f"{k}_" if k in forbidden_keys else k
                lines.append(f"{sanitized_k} = {val}")
            return "\n".join(lines)
        
        if isinstance(v, list):
            lines = []
            for item in v:
                if isinstance(item, str):
                    lines.append(item)
                elif isinstance(item, dict):
                    if "name" in item and "default" in item:
                        name = item['name']
                        val = item.get("default", item.get("value"))
                        sanitized_name = f"{name}_" if name in forbidden_keys else name
                        lines.append(f"{sanitized_name} = {val}")
                    elif "name" in item and "value" in item:
                         name = item['name']
                         sanitized_name = f"{name}_" if name in forbidden_keys else name
                         lines.append(f"{sanitized_name} = {item['value']}")
                    else:
                        for k, val in item.items():
                            sanitized_k = f"{k}_" if k in forbidden_keys else k
                            lines.append(f"{sanitized_k} = {val}")
            return "\n".join(lines)
            
        return v

    @field_validator('init_indicators')
    @classmethod
    def normalize_indicators(cls, v):
        if isinstance(v, list):
            return "\n".join(v)
        return v

    @field_validator('next_logic')
    @classmethod
    def normalize_logic(cls, v):
        if isinstance(v, list):
            return "\n".join(v)
        return v

# --- 4. PROMPT & PARSING ---
CODER_SYSTEM_PROMPT = """
ROLE: Senior Python Quant Developer specialized in the 'backtesting.py' framework.
TASK: Convert the provided English/JSON trading logic into specific Python code blocks.

--- TEMPLATE API ---
1. DATA: Use `self.close_s`, `self.high_s`, `self.low_s` (Pandas Series) for indicators.
   - ❌ WRONG: `ta.sma(self.data.Close)` -> CRASHES (Numpy array)
   - ✅ CORRECT: `ta.sma(self.close_s)`  -> WORKS (Pandas Series)
   - `self.data` is available for price checks in `next()`, NOT for `self.I`.
2. EXECUTION: `self.entry_long()`, `self.entry_short()`, `self.exit_all()`.
3. INDICATORS: Use `pandas_ta` as `ta`. WRAP ALL INDICATORS in `self.I()`.
   CRITICAL: Most TA-Lib functions (ATR, STOCH, ADX) need High, Low, AND Close.
   CORRECT: `self.atr = self.I(ta.atr, self.high_s, self.low_s, self.close_s, 14)`
   WRONG: `self.atr = self.I(ta.atr, self.close_s, 14)` -> THIS WILL CRASH.

--- RULES ---
1. `class_parameters`: Define numeric optimization variables.
   CRITICAL: Do NOT use Python reserved keywords (e.g., `lambda`, `class`, `import`). Use `lambda_val` or `lambda_param`.
2. `init_indicators`: Calculate indicators using `self.I`.
   CRITICAL: Do NOT use `ta.volatility`, `ta.trend` etc directly. They are modules. Use specific functions like `ta.atr`, `ta.bbands`, `ta.sma`.
   CRITICAL: ALWAYS provide `self.high_s, self.low_s, self.close_s` for volatility/trend indicators unless it's a simple MA.
   
   ALLOWED PANDAS_TA FUNCTIONS (STRICT WHITELIST):
   - ta.sma, ta.ema, ta.rsi, ta.macd, ta.bbands, ta.atr, ta.stoch, ta.adx, ta.cci, ta.roc, ta.willr, ta.aroon, ta.obv
   
   FORBIDDEN FUNCTIONS (Anti-Hallucination):
   - ❌ `ta.max` / `ta.min` (DOES NOT EXIST) -> Use `self.close_s.rolling(n).max()`.
   - ❌ `ta.correlation` (DOES NOT EXIST) -> Use `self.close_s.rolling(n).corr(other)`.
   - ❌ `ta.rolling_mean` -> Use `ta.sma`.
   - ❌ `ta.cross` -> Use `backtesting.lib.crossover`.
   - ❌ `ta.lowest` / `ta.highest` -> Use `series.rolling().min()`.
   
   CRITICAL PATTERNS:
   - ❌ LAMBDA FUNCTIONS IN self.I(): `self.I(lambda x: ...)` CRASHES. Use named functions only.
   - **CRITICAL SCOPE RULE**: Helper functions passed to `self.I()` MUST be PURE. They cannot access `self` or variables defined outside them (like `range_period` defined in `init`).
     - ❌ BAD: `def my_func(x): return x > period` (NameError: period is not defined)
     - ✅ GOOD: Pass `period` as an argument: `def my_func(x, p): return x > p` -> `self.I(my_func, self.data.Close, period)`
   - **CRITICAL**: NEVER use `self.I()` inside `next_logic`. `self.I` computes the entire indicator array once. Using it in `next()` is a logic error and causes crashes. Only use `self.I` in `init_indicators`.
   - **CRITICAL**: NEVER use Arrays/Indicators as parameters for other indicators. `length` or `timeperiod` must be STATIC INT.
     - BAD: `self.I(ta.sma, self.close_s, length=int(self.atr))` -> CRASHES
     - GOOD: `self.I(ta.sma, self.close_s, length=20)`
   - **CRITICAL**: `self.position` does NOT have `entry_price`.
   - **WARNING**: Volume indicators (OBV, VWAP, MFI) often return `None` or `NaN` on Forex/Crypto if volume is missing. Use `try/except` or fallback.
   - **CRITICAL**: `self.data.Close` (and High, Low, Open) are wrapped `_Array` objects (Numpy-based). They DO NOT have `.shift()` method. 
      - ❌ `self.data.Close.shift(1)` -> CRASHES.
      - ✅ Use slicing: `self.data.Close[-2]`.
      - ✅ Or cast to Series: `pd.Series(self.data.Close).shift(1)`.
   - **CRITICAL SYNTAX RULE**: If you use `try:`, you MUST include an `except` or `finally` block immediately after. DO NOT leave a `try` block pending.

3. `next_logic`: Per-candle logic. Use `self.data.Close[-1]`.
   - **NaN SAFETY**: Indicators like SMA(200) are NaN for first 200 candles.
     - ✅ Check: `if len(self.rsi) < 20: return` (Length check)
     - ✅ Check: `if np.isnan(self.rsi[-1]): return` (NaN check)
   - Use `if not self.position:` for entry checks.
   - Use `self.entry_long()` or `self.entry_short()`. **Do NOT pass `size=` argument.**
   - AVOID hardcoded absolute prices (e.g. `> 50`). Use relative checks.
   - **PRICE SAFETY**: When using limit/stop orders: `limit=self.data.Close[-1] - 0.5 * self.atr[-1]`. ENSURE price > 0. Use `max(0.01, calculated_price)`.
   
   PnL-BASED EXIT PATTERN (Recommended):
   - Instead of tracking entry_price (which doesn't exist), use position PnL:
     ```
     if self.position:
         pnl_pct = self.position.pl_pct  # Current profit/loss percentage
         if pnl_pct > self.take_profit:
             self.exit_all()
         elif pnl_pct < -self.stop_loss:
             self.exit_all()
     ```
   - Define `take_profit = 0.05` (5%) and `stop_loss = 0.03` (3%) in class_parameters.

--- FEW-SHOT EXAMPLES ---

User Request: "MACD Crossover Strategy"
Output JSON:
{
  "class_parameters": [
    "macd_fast = 12",
    "macd_slow = 26",
    "macd_signal = 9"
  ],
  "init_indicators": [
    "# MACD returns a DataFrame, so we extract columns manually if needed or use simple logic",
    "# Ideally use ta.macd(close=self.close_s, fast=self.macd_fast ...)",
    "self.macd = self.I(ta.macd, self.close_s, fast=self.macd_fast, slow=self.macd_slow, signal=self.macd_signal)"
  ],
  "next_logic": [
    "# MACD usually returns columns: MACD_12_26_9, MACDh_12_26_9, MACDs_12_26_9",
    "# But backtesting.py self.I wraps result. Implementation varies.",
    "# SAFER: Use ta.sma crossovers",
    "pass # (This example is mainly for syntax)"
  ]
}

User Request: "Bollinger Band Breakout"
Output JSON:
{
  "class_parameters": [
    "bb_period = 20",
    "bb_std = 2.0"
  ],
  "init_indicators": [
    "# Note: bbands returns 3 columns (Lower, Mid, Upper)",
    "self.bbands = self.I(ta.bbands, self.close_s, length=self.bb_period, std=self.bb_std)"
  ],
  "next_logic": [
    "if len(self.bbands) < 5:",
    "    return",
    "# Accessing tuple results from self.I can be tricky. ",
    "# Alternative: Calculate specifically what you need.",
    "lower_band = self.bbands[0] # Assuming tuple return structure",
    "upper_band = self.bbands[2]",
    "",
    "price = self.data.Close[-1]",
    "if not self.position:",
    "    if price > upper_band[-1]:",
    "        self.entry_long()",
    "    elif price < lower_band[-1]:",
    "        self.entry_short()"
  ]
}

User Request: "Fractal Breakout Strategy"
Output JSON:
{
  "class_parameters": "lookback = 5",
  "init_indicators": [
    "# Fractals: A high fractal is a bar where High is highest of lookback bars on each side",
    "# There is NO ta.fractals() function. Calculate manually using rolling max/min.",
    "def calc_fractal_high(h, n):",
    "    return h.rolling(n, center=True).max() == h",
    "def calc_fractal_low(l, n):",
    "    return l.rolling(n, center=True).min() == l",
    "",
    "self.fractal_high = self.I(calc_fractal_high, self.high_s, self.lookback)",
    "self.fractal_low = self.I(calc_fractal_low, self.low_s, self.lookback)",
    "self.highest = self.I(lambda h, n: h.rolling(n).max(), self.high_s, 20)",
    "self.lowest = self.I(lambda l, n: l.rolling(n).min(), self.low_s, 20)"
  ],
  "next_logic": [
    "if len(self.data) < 50: return",
    "price = self.data.Close[-1]",
    "",
    "# Breakout above the most recent fractal high",
    "if not self.position and price > self.highest[-2]:",
    "    self.entry_long()",
    "elif not self.position and price < self.lowest[-2]:",
    "    self.entry_short()"
  ]
}

User Request: "Exhaustion Pattern / Narrow Range Breakout"
Output JSON:
{
  "class_parameters": "nr_period = 4\\natr_period = 14",
  "init_indicators": [
    "# Exhaustion = Narrow Range bar (today's range is smallest of last N bars)",
    "# Calculate range manually",
    "def calc_range(h, l): return h - l",
    "self.bar_range = self.I(calc_range, self.high_s, self.low_s)",
    "self.atr = self.I(ta.atr, self.high_s, self.low_s, self.close_s, self.atr_period)"
  ],
  "next_logic": [
    "if len(self.data) < 50: return",
    "",
    "# Check if current bar is Narrow Range (smallest range in last N bars)",
    "curr_range = self.bar_range[-1]",
    "min_range = min(self.bar_range[-self.nr_period:])",
    "is_narrow = curr_range <= min_range * 1.1  # Within 10% of minimum",
    "",
    "# Breakout: price exceeds the narrow range bar's high/low",
    "prev_high = self.data.High[-2]",
    "prev_low = self.data.Low[-2]",
    "price = self.data.Close[-1]",
    "",
    "if not self.position and price > prev_high:",
    "    self.entry_long()",
    "elif not self.position and price < prev_low:",
    "    self.entry_short()"
  ]
}

--- OUTPUT ---
Return strictly a valid JSON object matching the schema.
- **Clean JSON Only**: Do not include markdown code blocks (```json ... ```) or any conversational text.
- **No Explanations**: Do not explain your code. Just provide the JSON.
- **Valid Python**: The string fields must contain valid, indentation-correct Python code.
"""

def extract_json_str(text: str) -> str:
    # 1. Strip code fences
    text = re.sub(r"```json", "", text, flags=re.IGNORECASE)
    text = re.sub(r"```", "", text)
    text = text.strip()
    
    # 2. Try strict regex for outer braces
    match = re.search(r"(\{.*\})", text, re.DOTALL)
    if match: 
        return match.group(1)
    return text

def parse_code_response(raw_text: str) -> PythonStrategyCode:
    json_str = extract_json_str(raw_text)
    
    # Helper to unwrap nested responses
    def unwrap_if_nested(data: dict) -> dict:
        """
        AI sometimes wraps response in {"PythonStrategyCode": {...}}.
        This unwraps it to get the inner dict.
        """
        if "PythonStrategyCode" in data and isinstance(data["PythonStrategyCode"], dict):
            return data["PythonStrategyCode"]
        # Also check for lowercase variant
        if "pythonStrategyCode" in data and isinstance(data["pythonStrategyCode"], dict):
            return data["pythonStrategyCode"]
        return data
    
    try:
        # First Try: Standard JSON
        import json
        parsed = json.loads(json_str)
        parsed = unwrap_if_nested(parsed)
        return TypeAdapter(PythonStrategyCode).validate_python(parsed)
    except Exception as e1:
        try:
            # Second Try: Python Dict Evaluation (Soft JSON)
            py_str = json_str.replace("true", "True").replace("false", "False").replace("null", "None")
            py_dict = ast.literal_eval(py_str)
            py_dict = unwrap_if_nested(py_dict)
            return TypeAdapter(PythonStrategyCode).validate_python(py_dict)
        except Exception as e2:
            logging.error(f"JSON Parse Failed. Raw: {json_str[:100]}... Error: {e2}")
            raise ValueError(f"Failed to parse AI response. JSON Error: {e1} | AST Error: {e2}")

# --- 5. THE AGENT ---
coder_agent = Agent(model=current_model)

# --- 6. KEY ROTATION ---
def rotate_coder_key(index: int):
    new_key = API_KEYS[index % len(API_KEYS)]
    coder_agent.model = create_model(new_key)
    logger.info(f"🔄 Coder switched to Key #{index % len(API_KEYS)}")